apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: todoapp
spec:
    containers:
    - name: busybox
      image: yurakolam/busyboxplus:curl
      imagePullPolicy: Always
      command: ["sleep", "1000"]
