apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
spec:
  containers:
    - name: todoapp
      image: konstant1nou77/todoapp:3.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /liveliness/  
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /readiness/
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
